ARG cni_tag

FROM ccr.ccs.tencentyun.com/tkeimages/cni-plugins-amd64:$cni_tag as CNI-Plugins

FROM ccr.ccs.tencentyun.com/tkeimages/multus-cni:v0.0.5 as Multus

FROM ccr.ccs.tencentyun.com/tkeimages/tke-eni:v1.0.3 as TKE-ENI

FROM alpine:3.6

WORKDIR /opt/cni/bin/

COPY --from=CNI-Plugins /opt/cni/bin/* ./

COPY --from=Multus /multus ./

COPY --from=TKE-ENI /opt/cni/bin/* ./

COPY scripts/install-cni.sh /

ENTRYPOINT ["/install-cni.sh"]
